services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/etc/otelcol-contrib/config.yaml:/etc/otelcol-contrib/config.yaml
    command: 
      - '--config'
      - '/etc/otelcol-contrib/config.yaml'
    ports:
      - 4317:4317
      - 8889:8889
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.docker/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:  
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=America/Sao_Paulo
    volumes:
      - ./.docker/grafana:/var/lib/grafana    
    ports:
      - 3000:3000

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 14268
      - 14250